### PR TITLE
Added code blocks and markup math for Chapter 7

### PR DESCRIPTION
**Pull request by bernakabadayi**

### CODE REVIEW

**Comment by hollasch** [comment]
These need to be marked up with math markup, rather than following the original italics or bold case.

For example, `Location is o + 3*x - 2*y + 7*z` should be `Location is $ o + 3\cdotx - 2\cdoty + 7\cdotz $`.

**Comment by hollasch** [comment]
For the pseudo-code, fence it off with generic code fence lines, like so:
```
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    If (fabs(n.x()) > 0.9)
        a = (0,1,0)
    else
        a = (1,0 ,0)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Note that the fences are 86 characters in length, and code blocks are indented four spaces.

**Review by hollasch — CHANGES_REQUESTED** [review]
See comments in conversation.

**Comment by hollasch** [comment]
_Ping_

**Comment by bernakabadayi** [comment]
Updated

**Comment by bernakabadayi** [comment]
This pull request closes #34 and #21

**Review by hollasch — APPROVED** [review]
Looks good; thanks!

**Pull request merged**
